/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Ariel
 */
public class JDialogBuscarArticulo extends javax.swing.JDialog implements InterfacePanel {

    private ValidadorDeCampos validador;
    /**
     * Creates new form JDialogBuscarUsuario
     */
    public JDialogBuscarArticulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.validador = new ValidadorDeCampos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaArticulo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneContenedor = new javax.swing.JTabbedPane();
        jPanelEmpleado = new javax.swing.JPanel();
        jlbl_descripcion = new javax.swing.JLabel();
        jlbl_ID = new javax.swing.JLabel();
        jtf_ID = new javax.swing.JTextField();
        jtf_descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcb_Unidad = new javax.swing.JComboBox<>();
        jlbl_unidad = new javax.swing.JLabel();
        jlbl_Categoria = new javax.swing.JLabel();
        jcb_Categoria = new javax.swing.JComboBox<>();
        jlbl_Proveedor = new javax.swing.JLabel();
        jcb_Proveedor = new javax.swing.JComboBox<>();
        jlbl_StockActual = new javax.swing.JLabel();
        jtf_stockActual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtn_Agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaDeArticulo = new javax.swing.JTable();
        jSpinnerArticulo = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jlbl_TituloListaDePrecio = new javax.swing.JLabel();
        jcb_Deposito = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jrb_Codigo = new javax.swing.JRadioButton();
        jrb_Descripcion = new javax.swing.JRadioButton();
        jrb_Proveedor = new javax.swing.JRadioButton();
        jtf_BuscarArticulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanelEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelEmpleado.setName("Empleado"); // NOI18N
        jPanelEmpleado.setLayout(null);

        jlbl_descripcion.setText("Descripción:");
        jPanelEmpleado.add(jlbl_descripcion);
        jlbl_descripcion.setBounds(20, 40, 100, 14);

        jlbl_ID.setText("ID:");
        jPanelEmpleado.add(jlbl_ID);
        jlbl_ID.setBounds(20, 10, 90, 14);
        jPanelEmpleado.add(jtf_ID);
        jtf_ID.setBounds(120, 10, 440, 20);
        jPanelEmpleado.add(jtf_descripcion);
        jtf_descripcion.setBounds(120, 40, 440, 20);
        jPanelEmpleado.add(jLabel1);
        jLabel1.setBounds(450, 40, 210, 0);

        jPanelEmpleado.add(jcb_Unidad);
        jcb_Unidad.setBounds(120, 70, 440, 22);

        jlbl_unidad.setText("Unidad:");
        jPanelEmpleado.add(jlbl_unidad);
        jlbl_unidad.setBounds(20, 70, 60, 14);

        jlbl_Categoria.setText("CATEGORIA:");
        jPanelEmpleado.add(jlbl_Categoria);
        jlbl_Categoria.setBounds(20, 100, 80, 14);

        jcb_Categoria.setEnabled(false);
        jPanelEmpleado.add(jcb_Categoria);
        jcb_Categoria.setBounds(120, 100, 440, 22);

        jlbl_Proveedor.setText("PROVEEDOR: ");
        jPanelEmpleado.add(jlbl_Proveedor);
        jlbl_Proveedor.setBounds(20, 130, 80, 14);

        jcb_Proveedor.setEnabled(false);
        jPanelEmpleado.add(jcb_Proveedor);
        jcb_Proveedor.setBounds(120, 130, 440, 22);

        jlbl_StockActual.setText("Stock Actual:");
        jPanelEmpleado.add(jlbl_StockActual);
        jlbl_StockActual.setBounds(20, 170, 90, 20);
        jPanelEmpleado.add(jtf_stockActual);
        jtf_stockActual.setBounds(120, 170, 440, 20);

        jTabbedPaneContenedor.addTab("Articulo", jPanelEmpleado);

        jPanel1.add(jTabbedPaneContenedor);
        jTabbedPaneContenedor.setBounds(10, 360, 580, 230);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Lista de Articulos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(730, 290));
        jPanel2.setLayout(null);

        jbtn_Agregar.setText("Agregar");
        jPanel2.add(jbtn_Agregar);
        jbtn_Agregar.setBounds(30, 170, 80, 30);

        tablaListaDeArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaListaDeArticulo);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 530, 130);

        jSpinnerArticulo.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerArticulo.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerArticulo, ""));
        jSpinnerArticulo.setEnabled(false);
        jPanel2.add(jSpinnerArticulo);
        jSpinnerArticulo.setBounds(510, 170, 50, 30);

        jLabel2.setText("CANTIDAD D ARTICULO:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(360, 170, 140, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 130, 580, 220);

        jlbl_TituloListaDePrecio.setText("Deposito: ");
        jPanel1.add(jlbl_TituloListaDePrecio);
        jlbl_TituloListaDePrecio.setBounds(20, 20, 80, 20);

        jcb_Deposito.setName(""); // NOI18N
        jPanel1.add(jcb_Deposito);
        jcb_Deposito.setBounds(110, 20, 190, 20);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Articulo por:"));
        jPanel4.setLayout(null);

        busquedaArticulo.add(jrb_Codigo);
        jrb_Codigo.setSelected(true);
        jrb_Codigo.setText("Codigo");
        jrb_Codigo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jrb_Codigo);
        jrb_Codigo.setBounds(10, 20, 80, 20);

        busquedaArticulo.add(jrb_Descripcion);
        jrb_Descripcion.setText("Descripción");
        jPanel4.add(jrb_Descripcion);
        jrb_Descripcion.setBounds(100, 20, 100, 20);

        busquedaArticulo.add(jrb_Proveedor);
        jrb_Proveedor.setText("Proveedor");
        jPanel4.add(jrb_Proveedor);
        jrb_Proveedor.setBounds(220, 20, 100, 20);
        jPanel4.add(jtf_BuscarArticulo);
        jtf_BuscarArticulo.setBounds(328, 20, 230, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 70, 580, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup busquedaArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerArticulo;
    private javax.swing.JTabbedPane jTabbedPaneContenedor;
    private javax.swing.JButton jbtn_Agregar;
    private javax.swing.JComboBox<String> jcb_Categoria;
    private javax.swing.JComboBox<String> jcb_Deposito;
    private javax.swing.JComboBox<String> jcb_Proveedor;
    private javax.swing.JComboBox<String> jcb_Unidad;
    private javax.swing.JLabel jlbl_Categoria;
    private javax.swing.JLabel jlbl_ID;
    private javax.swing.JLabel jlbl_Proveedor;
    private javax.swing.JLabel jlbl_StockActual;
    private javax.swing.JLabel jlbl_TituloListaDePrecio;
    private javax.swing.JLabel jlbl_descripcion;
    private javax.swing.JLabel jlbl_unidad;
    private javax.swing.JRadioButton jrb_Codigo;
    private javax.swing.JRadioButton jrb_Descripcion;
    private javax.swing.JRadioButton jrb_Proveedor;
    private javax.swing.JTextField jtf_BuscarArticulo;
    private javax.swing.JTextField jtf_ID;
    private javax.swing.JTextField jtf_descripcion;
    private javax.swing.JTextField jtf_stockActual;
    private javax.swing.JTable tablaListaDeArticulo;
    // End of variables declaration//GEN-END:variables


    @Override
    public void setControlador(Controller c) {
    try {
        //Agrega Botones al Escuchador ActionListener para manejar los eventos realizados
        jbtn_Agregar.addActionListener(c);
        
        
        //Agrega JTextField del Panel Datos del Empleado al escuchador KeyListener para verificar campos ingresados
        
        jtf_ID.addActionListener(c);
        jtf_descripcion.addActionListener(c);
        jtf_stockActual.addActionListener(c);
        
        
        jtf_BuscarArticulo.addKeyListener(c);
        jtf_BuscarArticulo.addFocusListener(c);
        
        //Agrego la tabla al escuchador Mouse Listener para verificar elementos seleccionados
        tablaListaDeArticulo.addMouseListener(c);
        
        //Botones de Radio        
        jrb_Codigo.addItemListener(c);
        jrb_Descripcion.addItemListener(c);
        jrb_Proveedor.addItemListener(c);
        
    } catch (Exception e) {
    }
        
    }

    @Override
    public void limpiarCampo(JTextField campo){
        campo.setText("");        
    }
    
    @Override
    public void habilitarCampo(boolean h, JTextField campo){
        campo.setEditable(h);
        
    }

    @Override
   public void habilitarBoton(boolean h, JButton btn){
       btn.setEnabled(h);
   }

    @Override
    public ValidadorDeCampos getValidador() {
        return validador;
    }
    

    @Override
    public void habilitarCombobox(boolean h, JComboBox campo) {
        campo.setEnabled(h);
    }

    @Override
    public void limpiarCombobox(JComboBox campo) {
        campo.removeAllItems();
    }

    public javax.swing.JSpinner getjSpinnerArticulo() {
        return jSpinnerArticulo;
    }

    public javax.swing.JButton getJbtn_Agregar() {
        return jbtn_Agregar;
    }

    public javax.swing.JComboBox<String> getJcb_Categoria() {
        return jcb_Categoria;
    }

    public javax.swing.JComboBox<String> getJcb_Deposito() {
        return jcb_Deposito;
    }

    public javax.swing.JComboBox<String> getJcb_Proveedor() {
        return jcb_Proveedor;
    }

    public javax.swing.JComboBox<String> getJcb_Unidad() {
        return jcb_Unidad;
    }

    public javax.swing.JRadioButton getJrb_Codigo() {
        return jrb_Codigo;
    }

    public javax.swing.JRadioButton getJrb_Descripcion() {
        return jrb_Descripcion;
    }

    public javax.swing.JRadioButton getJrb_Proveedor() {
        return jrb_Proveedor;
    }

    public javax.swing.JTextField getJtf_BuscarArticulo() {
        return jtf_BuscarArticulo;
    }

    public javax.swing.JTextField getJtf_ID() {
        return jtf_ID;
    }

    public javax.swing.JTextField getJtf_descripcion() {
        return jtf_descripcion;
    }

    public javax.swing.JTextField getJtf_stockActual() {
        return jtf_stockActual;
    }

    public javax.swing.JTable getTablaListaDeArticulo() {
        return tablaListaDeArticulo;
    }

    
    
    
}
