/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Ariel
 */
public class JDialogPagar extends javax.swing.JDialog implements InterfacePanel {

    private ValidadorDeCampos validador;
    /**
     * Constructor JDialog Buscar Deposito
     * @param parent padre al que pertenece
     * @param modal mientras este activo el JDialog todos los demas elementos quedan inactivos
     */
    public JDialogPagar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.validador = new ValidadorDeCampos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_Total = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_Pago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_Cambio = new javax.swing.JTextField();
        jcb_TipoPago = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jbtn_Pagar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Tipo Pago");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 220, 70, 20);

        jtf_Total.setEnabled(false);
        jPanel1.add(jtf_Total);
        jtf_Total.setBounds(270, 170, 140, 20);

        jLabel2.setText("Pago");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 280, 70, 20);

        jtf_Pago.setEnabled(false);
        jPanel1.add(jtf_Pago);
        jtf_Pago.setBounds(270, 280, 140, 20);

        jLabel3.setText("Cambio");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 320, 70, 20);

        jtf_Cambio.setEnabled(false);
        jPanel1.add(jtf_Cambio);
        jtf_Cambio.setBounds(270, 320, 140, 20);

        jcb_TipoPago.setEnabled(false);
        jPanel1.add(jcb_TipoPago);
        jcb_TipoPago.setBounds(270, 220, 140, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Registrar Pago");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 50, 240, 50);

        jbtn_Pagar.setText("PAGAR");
        jPanel1.add(jbtn_Pagar);
        jbtn_Pagar.setBounds(190, 410, 220, 40);

        jLabel5.setText("Total");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 170, 70, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_Pagar;
    private javax.swing.JComboBox<String> jcb_TipoPago;
    private javax.swing.JTextField jtf_Cambio;
    private javax.swing.JTextField jtf_Pago;
    private javax.swing.JTextField jtf_Total;
    // End of variables declaration//GEN-END:variables


    @Override
    public void setControlador(Controller c) {
    try {
        jtf_Cambio.addActionListener(c);
        jtf_Total.addActionListener(c);
        jtf_Pago.addActionListener(c);
        
        jtf_Cambio.addKeyListener(c);
        jtf_Total.addKeyListener(c);
        jtf_Pago.addKeyListener(c);
        
        jcb_TipoPago.addItemListener(c);
        jcb_TipoPago.addFocusListener(c);
        
        jbtn_Pagar.addActionListener(c);
        
    } catch (Exception e) {
    }
        
    }

    @Override
    public void limpiarCampo(JTextField campo){
        campo.setText("");        
    }
    
    @Override
    public void habilitarCampo(boolean h, JTextField campo){
        campo.setEditable(h);
        
    }

    @Override
   public void habilitarBoton(boolean h, JButton btn){
       btn.setEnabled(h);
   }

    @Override
    public ValidadorDeCampos getValidador() {
        return validador;
    }
    

    @Override
    public void habilitarCombobox(boolean h, JComboBox campo) {
        campo.setEnabled(h);
    }

    @Override
    public void limpiarCombobox(JComboBox campo) {
        campo.removeAllItems();
    }

    public javax.swing.JButton getJbtn_Pagar() {
        return jbtn_Pagar;
    }

    public void setJbtn_Pagar(javax.swing.JButton jbtn_Pagar) {
        this.jbtn_Pagar = jbtn_Pagar;
    }

    public javax.swing.JComboBox<String> getJcb_TipoPago() {
        return jcb_TipoPago;
    }

    public void setJcb_TipoPago(javax.swing.JComboBox<String> jcb_TipoPago) {
        this.jcb_TipoPago = jcb_TipoPago;
    }

    public javax.swing.JTextField getJtf_Cambio() {
        return jtf_Cambio;
    }

    public void setJtf_Cambio(javax.swing.JTextField jtf_Cambio) {
        this.jtf_Cambio = jtf_Cambio;
    }

    public javax.swing.JTextField getJtf_Pago() {
        return jtf_Pago;
    }

    public void setJtf_Pago(javax.swing.JTextField jtf_Pago) {
        this.jtf_Pago = jtf_Pago;
    }

    public javax.swing.JTextField getJtf_Total() {
        return jtf_Total;
    }

    public void setJtf_Total(javax.swing.JTextField jtf_Total) {
        this.jtf_Total = jtf_Total;
    }
    
    
    
}
