/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Ariel
 */
public class JDialogPagar extends javax.swing.JDialog implements InterfacePanel {

    private ValidadorDeCampos validador;
    /**
     * Constructor JDialog Buscar Deposito
     * @param parent padre al que pertenece
     * @param modal mientras este activo el JDialog todos los demas elementos quedan inactivos
     */
    public JDialogPagar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.validador = new ValidadorDeCampos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_subTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_Total = new javax.swing.JTextField();
        jcb_TipoPago = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jbtn_Pagar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtf_IVA = new javax.swing.JTextField();
        jlbl_IVA = new javax.swing.JLabel();
        jtf_Descuento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Tipo Pago");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 300, 70, 20);

        jtf_subTotal.setEnabled(false);
        jPanel1.add(jtf_subTotal);
        jtf_subTotal.setBounds(270, 140, 140, 20);

        jLabel3.setText("Total");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 350, 70, 20);

        jtf_Total.setEnabled(false);
        jPanel1.add(jtf_Total);
        jtf_Total.setBounds(270, 350, 140, 20);

        jcb_TipoPago.setEnabled(false);
        jPanel1.add(jcb_TipoPago);
        jcb_TipoPago.setBounds(270, 300, 140, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Registrar Pago");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 50, 240, 50);

        jbtn_Pagar.setText("PAGAR");
        jPanel1.add(jbtn_Pagar);
        jbtn_Pagar.setBounds(190, 410, 220, 40);

        jLabel5.setText("Sub-Total");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 140, 70, 20);

        jtf_IVA.setEnabled(false);
        jPanel1.add(jtf_IVA);
        jtf_IVA.setBounds(270, 190, 140, 20);

        jlbl_IVA.setText("IVA");
        jPanel1.add(jlbl_IVA);
        jlbl_IVA.setBounds(190, 190, 70, 20);

        jtf_Descuento.setEnabled(false);
        jPanel1.add(jtf_Descuento);
        jtf_Descuento.setBounds(270, 250, 140, 20);

        jLabel7.setText("Descuento");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 250, 70, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_Pagar;
    private javax.swing.JComboBox<String> jcb_TipoPago;
    private javax.swing.JLabel jlbl_IVA;
    private javax.swing.JTextField jtf_Descuento;
    private javax.swing.JTextField jtf_IVA;
    private javax.swing.JTextField jtf_Total;
    private javax.swing.JTextField jtf_subTotal;
    // End of variables declaration//GEN-END:variables


    @Override
    public void setControlador(Controller c) {
    try {
        jtf_Total.addActionListener(c);
        jtf_subTotal.addActionListener(c);
        jtf_IVA.addActionListener(c);
        jtf_Descuento.addActionListener(c);
        
        jtf_Total.addKeyListener(c);
        jtf_subTotal.addKeyListener(c);
        jtf_IVA.addKeyListener(c);
        jtf_Descuento.addKeyListener(c);
        
        jcb_TipoPago.addItemListener(c);
        jcb_TipoPago.addFocusListener(c);
        
        jbtn_Pagar.addActionListener(c);
        
        
        
    } catch (Exception e) {
    }
        
    }

    @Override
    public void limpiarCampo(JTextField campo){
        campo.setText("");        
    }
    
    @Override
    public void habilitarCampo(boolean h, JTextField campo){
        campo.setEditable(h);
        
    }

    @Override
   public void habilitarBoton(boolean h, JButton btn){
       btn.setEnabled(h);
   }

    @Override
    public ValidadorDeCampos getValidador() {
        return validador;
    }
    

    @Override
    public void habilitarCombobox(boolean h, JComboBox campo) {
        campo.setEnabled(h);
    }

    @Override
    public void limpiarCombobox(JComboBox campo) {
        campo.removeAllItems();
    }

    public javax.swing.JButton getJbtn_Pagar() {
        return jbtn_Pagar;
    }

    public void setJbtn_Pagar(javax.swing.JButton jbtn_Pagar) {
        this.jbtn_Pagar = jbtn_Pagar;
    }

    public javax.swing.JComboBox<String> getJcb_TipoPago() {
        return jcb_TipoPago;
    }

    public void setJcb_TipoPago(javax.swing.JComboBox<String> jcb_TipoPago) {
        this.jcb_TipoPago = jcb_TipoPago;
    }


    public javax.swing.JTextField getJtf_subTotal() {
        return jtf_subTotal;
    }

    public void setJtf_subTotal(javax.swing.JTextField jtf_Total) {
        this.jtf_subTotal = jtf_Total;
    }

    public javax.swing.JTextField getJtf_Descuento() {
        return jtf_Descuento;
    }

    public void setJtf_Descuento(javax.swing.JTextField jtf_Descuento) {
        this.jtf_Descuento = jtf_Descuento;
    }

    public javax.swing.JTextField getJtf_IVA() {
        return jtf_IVA;
    }

    public void setJtf_IVA(javax.swing.JTextField jtf_IVA) {
        this.jtf_IVA = jtf_IVA;
    }

    public javax.swing.JTextField getJtf_Total() {
        return jtf_Total;
    }

    public void setJtf_Total(javax.swing.JTextField jtf_Total) {
        this.jtf_Total = jtf_Total;
    }

    public javax.swing.JLabel getJlbl_IVA() {
        return jlbl_IVA;
    }

    public void setJlbl_IVA(javax.swing.JLabel jlbl_IVA) {
        this.jlbl_IVA = jlbl_IVA;
    }
    
    
    
}
