/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.EmpleadoController;
import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Ariel
 */
public class JframePrincipal extends javax.swing.JFrame implements InterfaceView{

    public static javax.swing.JPanel getjPanelArbol() {
        return jPanelArbol;
    }

    public static void setjPanelArbol(javax.swing.JPanel ajPanelArbol) {
        jPanelArbol = ajPanelArbol;
    }

    /**
     * Creates new form PersonaView
     */
    private static PanelArbol unPanelArbol = null;
    PanelContenedor unPanelContenedor = null;
    public JframePrincipal() {
        try {
            //Icono de la aplicacion
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());
            
        } catch (Exception e) {
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        JpanelContenedor = new javax.swing.JPanel();
        jPanelContenido = new javax.swing.JPanel();
        jPanelArbol = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GuraSoft");
        setMaximumSize(new java.awt.Dimension(1200, 821));
        setMinimumSize(new java.awt.Dimension(1200, 821));
        setResizable(false);

        JpanelContenedor.setMaximumSize(new java.awt.Dimension(1200, 821));
        JpanelContenedor.setPreferredSize(new java.awt.Dimension(1200, 821));
        JpanelContenedor.setLayout(null);

        jPanelContenido.setBackground(new java.awt.Color(0, 0, 0));
        jPanelContenido.setMaximumSize(null);
        jPanelContenido.setMinimumSize(new java.awt.Dimension(950, 800));
        jPanelContenido.setPreferredSize(new java.awt.Dimension(950, 800));
        jPanelContenido.setRequestFocusEnabled(false);
        jPanelContenido.setLayout(null);
        JpanelContenedor.add(jPanelContenido);
        jPanelContenido.setBounds(350, 0, 950, 800);

        jPanelArbol.setBackground(new java.awt.Color(255, 153, 204));
        jPanelArbol.setAutoscrolls(true);
        jPanelArbol.setMaximumSize(new java.awt.Dimension(350, 1200));
        jPanelArbol.setMinimumSize(new java.awt.Dimension(350, 800));
        jPanelArbol.setPreferredSize(new java.awt.Dimension(350, 800));
        jPanelArbol.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelArbolAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanelArbol.setLayout(null);
        JpanelContenedor.add(jPanelArbol);
        jPanelArbol.setBounds(0, 0, 350, 800);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelArbolAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelArbolAncestorAdded
        jPanelContenido.repaint();
        jPanelArbol.repaint();
    }//GEN-LAST:event_jPanelArbolAncestorAdded



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelContenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JPanel jPanelArbol;
    public static javax.swing.JPanel jPanelContenido;
    // End of variables declaration//GEN-END:variables



    @Override
    public void arranca() {
        unPanelArbol = new PanelArbol();
        unPanelArbol.setSize(350, 800);
        unPanelArbol.setLocation(0, 0);
 
        unPanelContenedor = new PanelContenedor();
        unPanelContenedor.setSize(950, 800);
        unPanelContenedor.setLocation(0, 0);
       
       jPanelArbol.removeAll();
       jPanelArbol.add(unPanelArbol, BorderLayout.NORTH);
       jPanelArbol.repaint();
       
       jPanelContenido.removeAll();
       jPanelContenido.add(unPanelContenedor, BorderLayout.NORTH);
       jPanelContenido.repaint();
        setLocationRelativeTo(null);// centra la ventana en la pantalla
        setVisible(true);// visualiza la ventana
    }

    public static void modificarArbol(boolean valor) {
            unPanelArbol.modificarArbol(valor);

    }

    

    
    
    
}
