/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.CatalogoCategoriaController;
import controller.ClienteController;
import controller.Conexion;
import controller.EmpleadoController;
import controller.EmpresaController;
import controller.ProveedorController;
import model.JPAController.EmpleadoJpaController;
import java.awt.BorderLayout;
import javax.swing.tree.TreePath;
import model.JPAController.CategoriaArticuloJpaController;
import model.JPAController.ClienteJpaController;
import model.JPAController.EmpresaJpaController;
import model.JPAController.ProveedorJpaController;
import static view.JframePrincipal.jPanelContenido;

/**
 *
 * @author Ariel
 */
public class PanelArbolAdministrador extends javax.swing.JPanel{

    /**
     * Creates new form PanelArbolAdministrador
     */
    String captura=null;       
    public PanelArbolAdministrador() {
        //Se crea Conexion para manejar JPA
        new  Conexion();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneArbol = new javax.swing.JScrollPane();
        panelContenedorArbol = new javax.swing.JPanel();
        arbolModulos = new javax.swing.JTree();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(350, 1200));
        setMinimumSize(new java.awt.Dimension(350, 800));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(350, 800));
        setLayout(null);

        jScrollPaneArbol.setAlignmentX(0.0F);
        jScrollPaneArbol.setAlignmentY(0.0F);

        panelContenedorArbol.setAlignmentX(0.0F);
        panelContenedorArbol.setAlignmentY(0.0F);
        panelContenedorArbol.setAutoscrolls(true);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("GuraSoft");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Administración General");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empresa");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empleados");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Catalogo");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Categoria");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Unidad Comercial");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Articulos");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Tablas Relativas a Articulos");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Articulos");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Lista de Precios");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Stock");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Depositos");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Sectores");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Ingreso de Movimientos");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Consulta y Baja de Movimientos");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Informes");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Compras");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Proveedores");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Ingreso de Comprobantes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Consulta y Baja de Comprobantes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Informes");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ventas");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Vendedores");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Descuentos y Rangos Varios");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Fecha de Facturación");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Definición para el ingreso de comprobantes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Ingreso de Comprobantes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Consulta y Baja de Comprobantes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Anulación de Comprobantes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Informes");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Cuentas a Cobrar");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Cobranzas");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Ingreso de Saldos Iniciales");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Consulta y Baja de Comprobantes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Informes");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Cuentas a Pagar");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Pagos");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Consulta y Baja de Comprobantes");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Informes");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Unidad de Sistemas");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ordenes de Trabajo");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arbolModulos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolModulos.setAlignmentX(0.0F);
        arbolModulos.setAlignmentY(0.0F);
        arbolModulos.setMaximumSize(new java.awt.Dimension(300, 800));
        arbolModulos.setMinimumSize(new java.awt.Dimension(300, 800));
        arbolModulos.setName(""); // NOI18N
        arbolModulos.setPreferredSize(new java.awt.Dimension(300, 800));
        arbolModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolModulosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorArbolLayout = new javax.swing.GroupLayout(panelContenedorArbol);
        panelContenedorArbol.setLayout(panelContenedorArbolLayout);
        panelContenedorArbolLayout.setHorizontalGroup(
            panelContenedorArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorArbolLayout.createSequentialGroup()
                .addComponent(arbolModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        panelContenedorArbolLayout.setVerticalGroup(
            panelContenedorArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorArbolLayout.createSequentialGroup()
                .addComponent(arbolModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jScrollPaneArbol.setViewportView(panelContenedorArbol);

        add(jScrollPaneArbol);
        jScrollPaneArbol.setBounds(0, 0, 350, 800);
    }// </editor-fold>//GEN-END:initComponents



    private void arbolModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolModulosMouseClicked
       
       
       TreePath tp = arbolModulos.getPathForLocation(evt.getX(), evt.getY());
       if (tp != null){
            captura = arbolModulos.getSelectionPath().toString();
            /*Intentanmos validar si la cadena equivale a vacio.
              Si ejecutamos nos daremos cuenta que esto
             genera una excepciòn ya que la cadena es nula*/

            if(captura.equals("[GuraSoft, Administración General, Empresa]")){  
            
                //Se crea el Panel Emplesa    
                PanelEmpresa unPanelEmpresa = new PanelEmpresa();            
                unPanelEmpresa.setSize(950, 800);
                unPanelEmpresa.setLocation(0,0);
                unPanelEmpresa.setVisible(true);

                //Se Crea controlador JPA
                EmpresaJpaController modelo = new EmpresaJpaController(Conexion.getEmf());

                //Se crea el controlador de Empresa
                EmpresaController controlador = new EmpresaController(unPanelEmpresa, modelo);

                //setea el panel para que sea escuchado por el controlador
                unPanelEmpresa.setControlador(controlador);


                jPanelContenido.removeAll();
                jPanelContenido.add(unPanelEmpresa, BorderLayout.NORTH);
                jPanelContenido.repaint();

                modificarArbol(false);
            }
            
            if(captura.equals("[GuraSoft, Administración General, Empleados]")){  
            
                //Se crea el Panel Empleado    
                PanelRegistroEmpleado unPanelPersona = new PanelRegistroEmpleado();            
                unPanelPersona.setSize(950, 800);
                unPanelPersona.setLocation(0,0);
                unPanelPersona.setVisible(true);

                //Se Crea controlador JPA
                EmpleadoJpaController modelo = new EmpleadoJpaController(Conexion.getEmf());

                //Se crea el controlador de Empleado
                EmpleadoController controlador = new EmpleadoController(unPanelPersona, modelo);

                //setea el panel para que sea escuchado por el controlador
                unPanelPersona.setControlador(controlador);


                jPanelContenido.removeAll();
                jPanelContenido.add(unPanelPersona, BorderLayout.NORTH);
                jPanelContenido.repaint();

                modificarArbol(false);
            }            
            
            if(captura.equals("[GuraSoft, Administración General, Catalogo, Categoria]")){  
            
                //Se crea el Panel Empleado    
                PanelRegistroCatalogoCategoria unPanelCategoria = new PanelRegistroCatalogoCategoria();            
                unPanelCategoria.setSize(950, 800);
                unPanelCategoria.setLocation(0,0);
                unPanelCategoria.setVisible(true);

                //Se Crea controlador JPA
                CategoriaArticuloJpaController modelo = new CategoriaArticuloJpaController(Conexion.getEmf());

                //Se crea el controlador de Empleado
                CatalogoCategoriaController controlador = new CatalogoCategoriaController(unPanelCategoria, modelo);

                //setea el panel para que sea escuchado por el controlador
                unPanelCategoria.setControlador(controlador);


                jPanelContenido.removeAll();
                jPanelContenido.add(unPanelCategoria, BorderLayout.NORTH);
                jPanelContenido.repaint();

                modificarArbol(false);
            } 
            
            
            if(captura.equals("[GuraSoft, Unidad Comercial, Compras, Proveedores]")){  
            
                //Se crea el Panel Proveedor    
                PanelRegistroProveedor unPanelProveedor = new PanelRegistroProveedor();            
                unPanelProveedor.setSize(950, 800);
                unPanelProveedor.setLocation(0,0);
                unPanelProveedor.setVisible(true);

                //Se Crea controlador JPA
                ProveedorJpaController modelo = new ProveedorJpaController(Conexion.getEmf());

                //Se crea el controlador de Proveedor
                ProveedorController controlador = new ProveedorController(unPanelProveedor, modelo);

                //setea el panel para que sea escuchado por el controlador
                unPanelProveedor.setControlador(controlador);


                jPanelContenido.removeAll();
                jPanelContenido.add(unPanelProveedor, BorderLayout.NORTH);
                jPanelContenido.repaint();

                modificarArbol(false);
            }
            
            if(captura.equals("[GuraSoft, Unidad Comercial, Ventas, Clientes]")){  
            
                //Se crea el Panel Cliente    
                PanelRegistroCliente unPanelCliente = new PanelRegistroCliente();            
                unPanelCliente.setSize(950, 800);
                unPanelCliente.setLocation(0,0);
                unPanelCliente.setVisible(true);

                //Se Crea controlador JPA
                ClienteJpaController modelo = new ClienteJpaController(Conexion.getEmf());

                //Se crea el controlador de Cliente
                ClienteController controlador = new ClienteController(unPanelCliente, modelo);

                //setea el panel para que sea escuchado por el controlador
                unPanelCliente.setControlador(controlador);


                jPanelContenido.removeAll();
                jPanelContenido.add(unPanelCliente, BorderLayout.NORTH);
                jPanelContenido.repaint();

                modificarArbol(false);
            }
            
       }else{
       
       
       
       }
    }//GEN-LAST:event_arbolModulosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolModulos;
    private javax.swing.JScrollPane jScrollPaneArbol;
    private javax.swing.JPanel panelContenedorArbol;
    // End of variables declaration//GEN-END:variables

    public void modificarArbol(boolean valor) {
        if (valor) {
            arbolModulos.setEnabled(true);
        }else {
            arbolModulos.setEnabled(false);
        }
         
    }

   

   

   
}
