/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;



/**
 *
 * @author Ariel
 */
public final class PanelRegistroProveedor extends javax.swing.JPanel  implements InterfacePanel{

    /**
     * Creates new form PersonalPanel
     */
    private ValidadorDeCampos validador;
    
    public PanelRegistroProveedor() {
        initComponents();      
        this.validador = new ValidadorDeCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtn_Nuevo = new javax.swing.JButton();
        jbtn_Modificar = new javax.swing.JButton();
        jbtn_Listar = new javax.swing.JButton();
        jbtn_Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jbtn_Volver = new javax.swing.JButton();
        jTabbedPaneContenedor = new javax.swing.JTabbedPane();
        jPanelEmpleado = new javax.swing.JPanel();
        jlbl_RazonSocial = new javax.swing.JLabel();
        jlbl_CUIT = new javax.swing.JLabel();
        jlbl_ID = new javax.swing.JLabel();
        jtf_ID = new javax.swing.JTextField();
        jtf_RazonSocial = new javax.swing.JTextField();
        jtf_CUIT = new javax.swing.JTextField();
        jPanelDireccion = new javax.swing.JPanel();
        jlbl_zona_direccion = new javax.swing.JLabel();
        jcb_zona_direccion = new javax.swing.JComboBox<>();
        jlbl_provincia_direccion = new javax.swing.JLabel();
        jcb_provincia_direccion = new javax.swing.JComboBox<>();
        jcb_localidad_direccion = new javax.swing.JComboBox<>();
        jlbl_localidad_direccion = new javax.swing.JLabel();
        jlbl_calle_direccion = new javax.swing.JLabel();
        jtf_calle_direccion = new javax.swing.JTextField();
        jtf_numero_direccion = new javax.swing.JTextField();
        jlbl_numero_direccion = new javax.swing.JLabel();
        jtf_piso_direccion = new javax.swing.JTextField();
        jlbl_piso_direccion = new javax.swing.JLabel();
        jtf_departamento_direccion = new javax.swing.JTextField();
        jlbl_departamento_direccion = new javax.swing.JLabel();
        jbtn_Aceptar = new javax.swing.JButton();
        jbtn_Cancelar = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(950, 800));
        setMinimumSize(new java.awt.Dimension(950, 800));
        setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Lista de Proveedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(730, 290));
        jPanel2.setLayout(null);

        jbtn_Nuevo.setText("Agregar");
        jPanel2.add(jbtn_Nuevo);
        jbtn_Nuevo.setBounds(30, 190, 80, 30);

        jbtn_Modificar.setText("Modificar");
        jPanel2.add(jbtn_Modificar);
        jbtn_Modificar.setBounds(120, 190, 90, 30);

        jbtn_Listar.setText("Listar");
        jPanel2.add(jbtn_Listar);
        jbtn_Listar.setBounds(220, 190, 80, 30);

        jbtn_Eliminar.setText("Eliminar");
        jPanel2.add(jbtn_Eliminar);
        jbtn_Eliminar.setBounds(310, 190, 80, 30);

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProveedores);
        if (tablaProveedores.getColumnModel().getColumnCount() > 0) {
            tablaProveedores.getColumnModel().getColumn(0).setMinWidth(120);
            tablaProveedores.getColumnModel().getColumn(0).setPreferredWidth(120);
            tablaProveedores.getColumnModel().getColumn(0).setMaxWidth(120);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 680, 150);

        add(jPanel2);
        jPanel2.setBounds(70, 50, 730, 230);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("GESTIÓN DE PROVEEDORES");
        add(jLabel4);
        jLabel4.setBounds(260, 10, 270, 30);

        jbtn_Volver.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbtn_Volver.setText("VOLVER");
        add(jbtn_Volver);
        jbtn_Volver.setBounds(590, 660, 210, 50);

        jPanelEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelEmpleado.setName("Empleado"); // NOI18N
        jPanelEmpleado.setLayout(null);

        jlbl_RazonSocial.setText("Razon Social:");
        jPanelEmpleado.add(jlbl_RazonSocial);
        jlbl_RazonSocial.setBounds(60, 100, 100, 15);

        jlbl_CUIT.setText("CUIT:");
        jPanelEmpleado.add(jlbl_CUIT);
        jlbl_CUIT.setBounds(60, 160, 80, 15);

        jlbl_ID.setText("ID:");
        jPanelEmpleado.add(jlbl_ID);
        jlbl_ID.setBounds(60, 40, 90, 15);
        jPanelEmpleado.add(jtf_ID);
        jtf_ID.setBounds(160, 40, 272, 19);
        jPanelEmpleado.add(jtf_RazonSocial);
        jtf_RazonSocial.setBounds(160, 100, 272, 19);
        jPanelEmpleado.add(jtf_CUIT);
        jtf_CUIT.setBounds(160, 160, 272, 19);

        jTabbedPaneContenedor.addTab("Proveedor", jPanelEmpleado);

        jPanelDireccion.setLayout(null);

        jlbl_zona_direccion.setText("Zona:");
        jPanelDireccion.add(jlbl_zona_direccion);
        jlbl_zona_direccion.setBounds(40, 30, 60, 15);

        jPanelDireccion.add(jcb_zona_direccion);
        jcb_zona_direccion.setBounds(150, 30, 180, 24);

        jlbl_provincia_direccion.setText("Provincia:");
        jPanelDireccion.add(jlbl_provincia_direccion);
        jlbl_provincia_direccion.setBounds(40, 70, 60, 15);

        jPanelDireccion.add(jcb_provincia_direccion);
        jcb_provincia_direccion.setBounds(150, 70, 180, 24);

        jPanelDireccion.add(jcb_localidad_direccion);
        jcb_localidad_direccion.setBounds(150, 110, 180, 24);

        jlbl_localidad_direccion.setText("Localidad:");
        jPanelDireccion.add(jlbl_localidad_direccion);
        jlbl_localidad_direccion.setBounds(40, 110, 60, 15);

        jlbl_calle_direccion.setText("Calle:");
        jPanelDireccion.add(jlbl_calle_direccion);
        jlbl_calle_direccion.setBounds(40, 150, 60, 15);
        jPanelDireccion.add(jtf_calle_direccion);
        jtf_calle_direccion.setBounds(150, 150, 180, 19);
        jPanelDireccion.add(jtf_numero_direccion);
        jtf_numero_direccion.setBounds(150, 180, 180, 19);

        jlbl_numero_direccion.setText("Número:");
        jPanelDireccion.add(jlbl_numero_direccion);
        jlbl_numero_direccion.setBounds(40, 180, 60, 15);
        jPanelDireccion.add(jtf_piso_direccion);
        jtf_piso_direccion.setBounds(150, 210, 180, 19);

        jlbl_piso_direccion.setText("Piso:");
        jPanelDireccion.add(jlbl_piso_direccion);
        jlbl_piso_direccion.setBounds(40, 210, 60, 15);
        jPanelDireccion.add(jtf_departamento_direccion);
        jtf_departamento_direccion.setBounds(150, 240, 180, 19);

        jlbl_departamento_direccion.setText("Departamento:");
        jPanelDireccion.add(jlbl_departamento_direccion);
        jlbl_departamento_direccion.setBounds(40, 240, 90, 15);

        jTabbedPaneContenedor.addTab("Dirección", jPanelDireccion);

        add(jTabbedPaneContenedor);
        jTabbedPaneContenedor.setBounds(70, 310, 730, 320);

        jbtn_Aceptar.setText("ACEPTAR");
        add(jbtn_Aceptar);
        jbtn_Aceptar.setBounds(70, 660, 170, 25);

        jbtn_Cancelar.setText("CANCELAR");
        add(jbtn_Cancelar);
        jbtn_Cancelar.setBounds(270, 660, 170, 25);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDireccion;
    private javax.swing.JPanel jPanelEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneContenedor;
    private javax.swing.JButton jbtn_Aceptar;
    private javax.swing.JButton jbtn_Cancelar;
    private javax.swing.JButton jbtn_Eliminar;
    private javax.swing.JButton jbtn_Listar;
    private javax.swing.JButton jbtn_Modificar;
    private javax.swing.JButton jbtn_Nuevo;
    private javax.swing.JButton jbtn_Volver;
    private javax.swing.JComboBox<String> jcb_localidad_direccion;
    private javax.swing.JComboBox<String> jcb_provincia_direccion;
    private javax.swing.JComboBox<String> jcb_zona_direccion;
    private javax.swing.JLabel jlbl_CUIT;
    private javax.swing.JLabel jlbl_ID;
    private javax.swing.JLabel jlbl_RazonSocial;
    private javax.swing.JLabel jlbl_calle_direccion;
    private javax.swing.JLabel jlbl_departamento_direccion;
    private javax.swing.JLabel jlbl_localidad_direccion;
    private javax.swing.JLabel jlbl_numero_direccion;
    private javax.swing.JLabel jlbl_piso_direccion;
    private javax.swing.JLabel jlbl_provincia_direccion;
    private javax.swing.JLabel jlbl_zona_direccion;
    private javax.swing.JTextField jtf_CUIT;
    private javax.swing.JTextField jtf_ID;
    private javax.swing.JTextField jtf_RazonSocial;
    private javax.swing.JTextField jtf_calle_direccion;
    private javax.swing.JTextField jtf_departamento_direccion;
    private javax.swing.JTextField jtf_numero_direccion;
    private javax.swing.JTextField jtf_piso_direccion;
    private javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void setControlador(Controller c) {
        
        //Agrega Botones al Escuchador ActionListener para manejar los eventos realizados
        jbtn_Nuevo.addActionListener(c);
        jbtn_Listar.addActionListener(c);
        jbtn_Modificar.addActionListener(c);
        jbtn_Eliminar.addActionListener(c);       
        jbtn_Aceptar.addActionListener(c);
        jbtn_Cancelar.addActionListener(c);      
        jbtn_Volver.addActionListener(c); 
        
        
        //Agrega JTextField del Panel Datos del Empleado al escuchador KeyListener para verificar campos ingresados
        jtf_RazonSocial.addKeyListener(c);
        jtf_CUIT.addKeyListener(c);
        
        //Agrega JTextField del Panel Direccion al escuchador KeyListener para verificar campos ingresados
        jtf_calle_direccion.addKeyListener(c);
        jtf_numero_direccion.addKeyListener(c);
        jtf_piso_direccion.addKeyListener(c);
        jtf_departamento_direccion.addKeyListener(c);
        
        //Agrega JcomboBox del Panel Direccion al escuchador ItemListener para verificar items seleccionados
        jcb_zona_direccion.addItemListener(c);
        jcb_provincia_direccion.addItemListener(c);
        jcb_localidad_direccion.addItemListener(c);
        
        //Agrega JcomboBox del Panel Direccion al escuchador ItemListener para verificar items seleccionados
        jcb_zona_direccion.addFocusListener(c);
        jcb_provincia_direccion.addFocusListener(c);
        jcb_localidad_direccion.addFocusListener(c);
        jtf_CUIT.addFocusListener(c);
        
        //Agrego la tabla al escuchador Mouse Listener para verificar elementos seleccionados
        tablaProveedores.addMouseListener(c);
        
        
        
    }

    /*
    CAMPOS del PANEL Getters y Setters
    */    

    public javax.swing.JTextField getJtfCUIT() {
        return jtf_CUIT;
    }

    public void setJtfCUIT(javax.swing.JTextField jtfCUIT) {
        this.jtf_CUIT = jtfCUIT;
    }
   
    public javax.swing.JTextField getJtfID() {
        return jtf_ID;
    }

    public void setJtfID(javax.swing.JTextField jtfID) {
        this.jtf_ID = jtfID;
    }

    public javax.swing.JTextField getJtfRazonSocial() {
        return jtf_RazonSocial;
    }

    public void setJtfRazonSocial(javax.swing.JTextField jtfRazonSocial) {
        this.jtf_RazonSocial = jtfRazonSocial;
    }

    public javax.swing.JComboBox<String> getJcb_localidad_direccion() {
        return jcb_localidad_direccion;
    }

    public void setJcb_localidad_direccion(javax.swing.JComboBox<String> jcb_localidad_direccion) {
        this.jcb_localidad_direccion = jcb_localidad_direccion;
    }

    public javax.swing.JComboBox<String> getJcb_provincia_direccion() {
        return jcb_provincia_direccion;
    }

    public void setJcb_provincia_direccion(javax.swing.JComboBox<String> jcb_provincia_direccion) {
        this.jcb_provincia_direccion = jcb_provincia_direccion;
    }

    public javax.swing.JComboBox<String> getJcb_zona_direccion() {
        return jcb_zona_direccion;
    }

    public void setJcb_zona_direccion(javax.swing.JComboBox<String> jcb_zona_direccion) {
        this.jcb_zona_direccion = jcb_zona_direccion;
    }

    public javax.swing.JTextField getJtf_calle_direccion() {
        return jtf_calle_direccion;
    }

    public void setJtf_calle_direccion(javax.swing.JTextField jtf_calle_direccion) {
        this.jtf_calle_direccion = jtf_calle_direccion;
    }

    public javax.swing.JTextField getJtf_departamento_direccion() {
        return jtf_departamento_direccion;
    }

    public void setJtf_departamento_direccion(javax.swing.JTextField jtf_departamento_direccion) {
        this.jtf_departamento_direccion = jtf_departamento_direccion;
    }

    public javax.swing.JTextField getJtf_numero_direccion() {
        return jtf_numero_direccion;
    }

    public void setJtf_numero_direccion(javax.swing.JTextField jtf_numero_direccion) {
        this.jtf_numero_direccion = jtf_numero_direccion;
    }

    public javax.swing.JTextField getJtf_piso_direccion() {
        return jtf_piso_direccion;
    }

    public void setJtf_piso_direccion(javax.swing.JTextField jtf_piso_direccion) {
        this.jtf_piso_direccion = jtf_piso_direccion;
    }
    
    
    
    /*
    BOTONES del PANEL
    */
        
    public javax.swing.JButton getJbtn_Aceptar() {
        return jbtn_Aceptar;
    }

    public javax.swing.JButton getJbtn_Cancelar() {
        return jbtn_Cancelar;
    }

    public javax.swing.JButton getJbtn_Eliminar() {
        return jbtn_Eliminar;
    }

    public javax.swing.JButton getJbtn_Listar() {
        return jbtn_Listar;
    }

    public javax.swing.JButton getJbtn_Modificar() {
        return jbtn_Modificar;
    }

    public javax.swing.JButton getJbtn_Agregar() {
        return jbtn_Nuevo;
    }

    public javax.swing.JButton getJbtn_Volver() {
        return jbtn_Volver;
    }
      
    
    
    @Override
    public void limpiarCampo(JTextField campo){
        campo.setText("");        
    }
    
    @Override
    public void habilitarCampo(boolean h, JTextField campo){
        campo.setEditable(h);
        
    }

    @Override
   public void habilitarBoton(boolean h, JButton btn){
       btn.setEnabled(h);
   }

    @Override
    public ValidadorDeCampos getValidador() {
        return validador;
    }

    public javax.swing.JTable getTablaProveedores() {
        return tablaProveedores;
    }

    @Override
    public void habilitarCombobox(boolean h, JComboBox campo) {
        campo.setEnabled(h);
    }

    @Override
    public void limpiarCombobox(JComboBox campo) {
        campo.removeAllItems();
    }

    public javax.swing.JPanel getjPanelDireccion() {
        return jPanelDireccion;
    }

    public javax.swing.JPanel getjPanelEmpleado() {
        return jPanelEmpleado;
    }

    public javax.swing.JTabbedPane getjTabbedPaneContenedor() {
        return jTabbedPaneContenedor;
    }

   
    
    
}
