/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EmpleadoController;

/**
 *
 * @author Ariel
 */
public class PanelRegistroEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PersonalPanel
     */
    public PanelRegistroEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbtnNuevo = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jtfID = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfDireccion = new javax.swing.JTextField();
        jtfEdad = new javax.swing.JTextField();
        jtfDNI = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(950, 800));
        setMinimumSize(new java.awt.Dimension(950, 800));
        setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 68, 100, 15);

        jLabel2.setText("Apellido:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 110, 90, 15);

        jLabel3.setText("DNI::");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 140, 80, 15);

        jLabel4.setText("Edad:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 180, 110, 15);

        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 210, 100, 15);

        jbtnBuscar.setText("Buscar");
        jPanel1.add(jbtnBuscar);
        jbtnBuscar.setBounds(440, 20, 80, 25);

        jLabel6.setText("ID:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 28, 90, 15);

        jbtnNuevo.setText("Nuevo");
        jPanel1.add(jbtnNuevo);
        jbtnNuevo.setBounds(130, 260, 80, 25);

        jbtnModificar.setText("Modificar");
        jPanel1.add(jbtnModificar);
        jbtnModificar.setBounds(220, 260, 90, 25);

        jbtnEliminar.setText("Eliminar");
        jPanel1.add(jbtnEliminar);
        jbtnEliminar.setBounds(320, 260, 80, 25);

        jtfID.setEnabled(false);
        jPanel1.add(jtfID);
        jtfID.setBounds(132, 24, 272, 19);

        jtfNombre.setEnabled(false);
        jPanel1.add(jtfNombre);
        jtfNombre.setBounds(132, 62, 272, 19);

        jtfDireccion.setEnabled(false);
        jPanel1.add(jtfDireccion);
        jtfDireccion.setBounds(132, 210, 272, 19);

        jtfEdad.setEnabled(false);
        jPanel1.add(jtfEdad);
        jtfEdad.setBounds(132, 173, 272, 19);

        jtfDNI.setEnabled(false);
        jPanel1.add(jtfDNI);
        jtfDNI.setBounds(132, 136, 272, 19);

        jtfApellido.setEnabled(false);
        jPanel1.add(jtfApellido);
        jtfApellido.setBounds(132, 99, 272, 19);

        add(jPanel1);
        jPanel1.setBounds(30, 210, 730, 290);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 730, 100);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfEdad;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables

    
    public void setControlador(EmpleadoController c) {
        jbtnNuevo.addActionListener(c);
        jbtnBuscar.addActionListener(c);
        jbtnModificar.addActionListener(c);
        jbtnEliminar.addActionListener(c);
        
    }

    public javax.swing.JTextField getJtfApellido() {
        return jtfApellido;
    }

    public void setJtfApellido(javax.swing.JTextField jtfApellido) {
        this.jtfApellido = jtfApellido;
    }

    public javax.swing.JTextField getJtfDNI() {
        return jtfDNI;
    }

    public void setJtfDNI(javax.swing.JTextField jtfDNI) {
        this.jtfDNI = jtfDNI;
    }

    public javax.swing.JTextField getJtfDireccion() {
        return jtfDireccion;
    }

    public void setJtfDireccion(javax.swing.JTextField jtfDireccion) {
        this.jtfDireccion = jtfDireccion;
    }

    public javax.swing.JTextField getJtfEdad() {
        return jtfEdad;
    }

    public void setJtfEdad(javax.swing.JTextField jtfEdad) {
        this.jtfEdad = jtfEdad;
    }

    public javax.swing.JTextField getJtfID() {
        return jtfID;
    }

    public void setJtfID(javax.swing.JTextField jtfID) {
        this.jtfID = jtfID;
    }

    public javax.swing.JTextField getJtfNombre() {
        return jtfNombre;
    }

    public void setJtfNombre(javax.swing.JTextField jtfNombre) {
        this.jtfNombre = jtfNombre;
    }

    public javax.swing.JButton getJbtnBuscar() {
        return jbtnBuscar;
    }

    public javax.swing.JButton getJbtnEliminar() {
        return jbtnEliminar;
    }

    public javax.swing.JButton getJbtnModificar() {
        return jbtnModificar;
    }

    public javax.swing.JButton getJbtnNuevo() {
        return jbtnNuevo;
    }
    
}
