/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import model.JPAController.Conexion;
import controller.EmpleadoController;
import controller.VentaController;
import model.JPAController.EmpleadoJpaController;
import java.awt.BorderLayout;
import javax.swing.tree.TreePath;
import model.JPAController.VentaJpaController;
import static view.JframePrincipal.jPanelContenido;

/**
 *
 * @author Ariel
 */
public class PanelArbolUsuario extends javax.swing.JPanel{

    /**
     * Creates new form PanelArbolAdministrador
     */
    String captura=null;       
    public PanelArbolUsuario() {
        //Se crea Conexion para manejar JPA
        new  Conexion();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneArbol = new javax.swing.JScrollPane();
        panelContenedorArbol = new javax.swing.JPanel();
        arbolModulos = new javax.swing.JTree();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(350, 1200));
        setMinimumSize(new java.awt.Dimension(350, 800));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(350, 800));
        setLayout(null);

        jScrollPaneArbol.setAlignmentX(0.0F);
        jScrollPaneArbol.setAlignmentY(0.0F);

        panelContenedorArbol.setAlignmentX(0.0F);
        panelContenedorArbol.setAlignmentY(0.0F);
        panelContenedorArbol.setAutoscrolls(true);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("GuraSoft");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Articulos");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Articulos");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ventas");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ingreso de Comprobantes");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Informes");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arbolModulos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolModulos.setAlignmentX(0.0F);
        arbolModulos.setAlignmentY(0.0F);
        arbolModulos.setMaximumSize(new java.awt.Dimension(300, 800));
        arbolModulos.setMinimumSize(new java.awt.Dimension(300, 800));
        arbolModulos.setName(""); // NOI18N
        arbolModulos.setPreferredSize(new java.awt.Dimension(300, 800));
        arbolModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolModulosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorArbolLayout = new javax.swing.GroupLayout(panelContenedorArbol);
        panelContenedorArbol.setLayout(panelContenedorArbolLayout);
        panelContenedorArbolLayout.setHorizontalGroup(
            panelContenedorArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorArbolLayout.createSequentialGroup()
                .addComponent(arbolModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        panelContenedorArbolLayout.setVerticalGroup(
            panelContenedorArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorArbolLayout.createSequentialGroup()
                .addComponent(arbolModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jScrollPaneArbol.setViewportView(panelContenedorArbol);

        add(jScrollPaneArbol);
        jScrollPaneArbol.setBounds(0, 0, 350, 800);
    }// </editor-fold>//GEN-END:initComponents



    private void arbolModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolModulosMouseClicked
       
       
       TreePath tp = arbolModulos.getPathForLocation(evt.getX(), evt.getY());
       if (tp != null){
            captura = arbolModulos.getSelectionPath().toString();
            /*Intentanmos validar si la cadena equivale a vacio.
              Si ejecutamos nos daremos cuenta que esto
             genera una excepciòn ya que la cadena es nula*/

            if(captura.equals("[GuraSoft, Ventas, Ingreso de Comprobantes]")){  
            
                //Se crea el Panel Cliente    
                PanelRegistroVenta unPanelVenta = new PanelRegistroVenta();            
                unPanelVenta.setSize(950, 750);
                unPanelVenta.setLocation(0,0);
                unPanelVenta.setVisible(true);

                //Se Crea controlador JPA
                VentaJpaController modelo = new VentaJpaController(Conexion.getEmf());

                //Se crea el controlador de Cliente
                VentaController controlador = new VentaController(unPanelVenta, modelo);

                //setea el panel para que sea escuchado por el controlador
                unPanelVenta.setControlador(controlador);


                jPanelContenido.removeAll();
                jPanelContenido.add(unPanelVenta, BorderLayout.NORTH);
                jPanelContenido.repaint();

                habilitarArbol(false);
            }
       }else{
       
       
       
       }
    }//GEN-LAST:event_arbolModulosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolModulos;
    private javax.swing.JScrollPane jScrollPaneArbol;
    private javax.swing.JPanel panelContenedorArbol;
    // End of variables declaration//GEN-END:variables

    public void habilitarArbol(boolean valor) {
        if (valor) {
            arbolModulos.setEnabled(true);
        }else {
            arbolModulos.setEnabled(false);
        }
         
    }

   

   

   
}
