/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EmpleadoController;
import controller.EmpresaController;
import javax.swing.JButton;
import javax.swing.JTextField;



/**
 *
 * @author Ariel
 */
public final class PanelEmpresa extends javax.swing.JPanel  implements InterfacePanel{

    /**
     * Creates new form PersonalPanel
     */
    private ValidadorDeCampos validador;
    
    public PanelEmpresa() {
        initComponents();      
        this.validador = new ValidadorDeCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_Nombre = new javax.swing.JLabel();
        jlbl_DNI = new javax.swing.JLabel();
        jlbl_Direccion = new javax.swing.JLabel();
        jlbl_ID = new javax.swing.JLabel();
        jtf_ID = new javax.swing.JTextField();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_Direccion = new javax.swing.JTextField();
        jtf_DNI = new javax.swing.JTextField();
        jbtn_Aceptar = new javax.swing.JButton();
        jbtn_Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        msj_Direccion = new javax.swing.JLabel();
        msj_ID = new javax.swing.JLabel();
        msj_Nombre = new javax.swing.JLabel();
        msj_Apellido = new javax.swing.JLabel();
        msj_DNI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtn_Volver = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(950, 800));
        setMinimumSize(new java.awt.Dimension(950, 800));
        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        jPanel1.setName("Empleado"); // NOI18N
        jPanel1.setLayout(null);

        jlbl_Nombre.setText("Razon Social");
        jPanel1.add(jlbl_Nombre);
        jlbl_Nombre.setBounds(60, 80, 90, 15);

        jlbl_DNI.setText("CUIT");
        jPanel1.add(jlbl_DNI);
        jlbl_DNI.setBounds(60, 120, 80, 15);

        jlbl_Direccion.setText("Dirección:");
        jPanel1.add(jlbl_Direccion);
        jlbl_Direccion.setBounds(60, 160, 100, 15);

        jlbl_ID.setText("ID:");
        jPanel1.add(jlbl_ID);
        jlbl_ID.setBounds(60, 40, 90, 15);
        jPanel1.add(jtf_ID);
        jtf_ID.setBounds(160, 40, 272, 19);
        jPanel1.add(jtf_Nombre);
        jtf_Nombre.setBounds(160, 80, 272, 19);
        jPanel1.add(jtf_Direccion);
        jtf_Direccion.setBounds(160, 160, 272, 19);
        jPanel1.add(jtf_DNI);
        jtf_DNI.setBounds(160, 120, 272, 19);

        jbtn_Aceptar.setText("ACEPTAR");
        jPanel1.add(jbtn_Aceptar);
        jbtn_Aceptar.setBounds(60, 240, 170, 25);

        jbtn_Cancelar.setText("CANCELAR");
        jPanel1.add(jbtn_Cancelar);
        jbtn_Cancelar.setBounds(260, 240, 170, 25);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 40, 210, 0);
        jPanel1.add(msj_Direccion);
        msj_Direccion.setBounds(480, 190, 34, 15);
        jPanel1.add(msj_ID);
        msj_ID.setBounds(480, 40, 0, 0);
        jPanel1.add(msj_Nombre);
        msj_Nombre.setBounds(480, 80, 0, 0);
        jPanel1.add(msj_Apellido);
        msj_Apellido.setBounds(480, 110, 0, 0);
        jPanel1.add(msj_DNI);
        msj_DNI.setBounds(480, 150, 0, 0);

        add(jPanel1);
        jPanel1.setBounds(70, 50, 730, 290);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("GESTIÓN DE EMPRESA");
        add(jLabel4);
        jLabel4.setBounds(300, 10, 250, 30);

        jbtn_Volver.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbtn_Volver.setText("VOLVER");
        add(jbtn_Volver);
        jbtn_Volver.setBounds(300, 650, 210, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_Aceptar;
    private javax.swing.JButton jbtn_Cancelar;
    private javax.swing.JButton jbtn_Volver;
    private javax.swing.JLabel jlbl_DNI;
    private javax.swing.JLabel jlbl_Direccion;
    private javax.swing.JLabel jlbl_ID;
    private javax.swing.JLabel jlbl_Nombre;
    private javax.swing.JTextField jtf_DNI;
    private javax.swing.JTextField jtf_Direccion;
    private javax.swing.JTextField jtf_ID;
    private javax.swing.JTextField jtf_Nombre;
    private javax.swing.JLabel msj_Apellido;
    private javax.swing.JLabel msj_DNI;
    private javax.swing.JLabel msj_Direccion;
    private javax.swing.JLabel msj_ID;
    private javax.swing.JLabel msj_Nombre;
    // End of variables declaration//GEN-END:variables

    
    public void setControlador(EmpresaController c) {
        
        
        jbtn_Aceptar.addActionListener(c);
        jbtn_Cancelar.addActionListener(c);
        
        jbtn_Volver.addActionListener(c);  
        
        //Agrega JTextField al escuchador
        jtf_Nombre.addKeyListener(c);
        jtf_Direccion.addKeyListener(c);
        jtf_DNI.addKeyListener(c);
        
    }

    /*
    CAMPOS del PANEL
    */    
    public javax.swing.JTextField getJtfDNI() {
        return jtf_DNI;
    }

    public void setJtfDNI(javax.swing.JTextField jtfDNI) {
        this.jtf_DNI = jtfDNI;
    }

    public javax.swing.JTextField getJtfDireccion() {
        return jtf_Direccion;
    }

    public void setJtfDireccion(javax.swing.JTextField jtfDireccion) {
        this.jtf_Direccion = jtfDireccion;
    }

    public javax.swing.JTextField getJtfID() {
        return jtf_ID;
    }

    public void setJtfID(javax.swing.JTextField jtfID) {
        this.jtf_ID = jtfID;
    }

    public javax.swing.JTextField getJtfNombre() {
        return jtf_Nombre;
    }

    public void setJtfNombre(javax.swing.JTextField jtfNombre) {
        this.jtf_Nombre = jtfNombre;
    }

    
    /*
    BOTONES del PANEL
    */
        
    public javax.swing.JButton getJbtn_Aceptar() {
        return jbtn_Aceptar;
    }

    public javax.swing.JButton getJbtn_Cancelar() {
        return jbtn_Cancelar;
    }


    public javax.swing.JButton getJbtn_Volver() {
        return jbtn_Volver;
    }
    
    
    @Override
    public void limpiarCampo(JTextField campo){
        campo.setText("");        
    }
    
    @Override
    public void habilitarCampo(boolean h, JTextField campo){
        campo.setEditable(h);
        
    }

    @Override
   public void habilitarBoton(boolean h, JButton btn){
       btn.setEnabled(h);
   }

    @Override
    public ValidadorDeCampos getValidador() {
        return validador;
    }

    
}
