/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;



/**
 *
 * @author Ariel
 */
public final class PanelEmpresa extends javax.swing.JPanel  implements InterfacePanel{

    /**
     * Creates new form PersonalPanel
     */
    private ValidadorDeCampos validador;
    
    public PanelEmpresa() {
        initComponents();      
        this.validador = new ValidadorDeCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jbtn_Volver = new javax.swing.JButton();
        jPanelEmpleado = new javax.swing.JPanel();
        jlbl_RazonSocial = new javax.swing.JLabel();
        jlbl_ID = new javax.swing.JLabel();
        jtf_ID = new javax.swing.JTextField();
        jtf_RazonSocial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        msj_Direccion = new javax.swing.JLabel();
        msj_ID = new javax.swing.JLabel();
        msj_Nombre = new javax.swing.JLabel();
        msj_Apellido = new javax.swing.JLabel();
        msj_DNI = new javax.swing.JLabel();
        jcb_provincia_direccion = new javax.swing.JComboBox<>();
        jcb_zona_direccion = new javax.swing.JComboBox<>();
        jlbl_zona_direccion = new javax.swing.JLabel();
        jlbl_provincia_direccion = new javax.swing.JLabel();
        jlbl_localidad_direccion = new javax.swing.JLabel();
        jlbl_calle_direccion = new javax.swing.JLabel();
        jlbl_numero_direccion = new javax.swing.JLabel();
        jlbl_piso_direccion = new javax.swing.JLabel();
        jlbl_departamento_direccion = new javax.swing.JLabel();
        jcb_localidad_direccion = new javax.swing.JComboBox<>();
        jtf_calle_direccion = new javax.swing.JTextField();
        jtf_numero_direccion = new javax.swing.JTextField();
        jtf_piso_direccion = new javax.swing.JTextField();
        jtf_departamento_direccion = new javax.swing.JTextField();
        jlbl_cuit = new javax.swing.JLabel();
        jtf_Cuit = new javax.swing.JTextField();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(950, 800));
        setMinimumSize(new java.awt.Dimension(950, 800));
        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Empresa");
        add(jLabel4);
        jLabel4.setBounds(360, 20, 90, 30);

        jbtn_Volver.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbtn_Volver.setText("VOLVER");
        add(jbtn_Volver);
        jbtn_Volver.setBounds(290, 520, 210, 50);

        jPanelEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelEmpleado.setName("Empleado"); // NOI18N
        jPanelEmpleado.setLayout(null);

        jlbl_RazonSocial.setText("Razon Social:");
        jPanelEmpleado.add(jlbl_RazonSocial);
        jlbl_RazonSocial.setBounds(30, 70, 100, 15);

        jlbl_ID.setText("ID:");
        jPanelEmpleado.add(jlbl_ID);
        jlbl_ID.setBounds(30, 30, 90, 15);
        jPanelEmpleado.add(jtf_ID);
        jtf_ID.setBounds(140, 30, 180, 19);
        jPanelEmpleado.add(jtf_RazonSocial);
        jtf_RazonSocial.setBounds(140, 70, 180, 19);
        jPanelEmpleado.add(jLabel1);
        jLabel1.setBounds(450, 40, 210, 0);
        jPanelEmpleado.add(msj_Direccion);
        msj_Direccion.setBounds(480, 190, 34, 15);
        jPanelEmpleado.add(msj_ID);
        msj_ID.setBounds(480, 40, 0, 0);
        jPanelEmpleado.add(msj_Nombre);
        msj_Nombre.setBounds(480, 80, 0, 0);
        jPanelEmpleado.add(msj_Apellido);
        msj_Apellido.setBounds(480, 110, 0, 0);
        jPanelEmpleado.add(msj_DNI);
        msj_DNI.setBounds(480, 150, 0, 0);

        jPanelEmpleado.add(jcb_provincia_direccion);
        jcb_provincia_direccion.setBounds(140, 190, 180, 24);

        jPanelEmpleado.add(jcb_zona_direccion);
        jcb_zona_direccion.setBounds(140, 150, 180, 24);

        jlbl_zona_direccion.setText("Zona:");
        jPanelEmpleado.add(jlbl_zona_direccion);
        jlbl_zona_direccion.setBounds(30, 150, 60, 15);

        jlbl_provincia_direccion.setText("Provincia:");
        jPanelEmpleado.add(jlbl_provincia_direccion);
        jlbl_provincia_direccion.setBounds(30, 190, 60, 15);

        jlbl_localidad_direccion.setText("Localidad:");
        jPanelEmpleado.add(jlbl_localidad_direccion);
        jlbl_localidad_direccion.setBounds(30, 230, 60, 15);

        jlbl_calle_direccion.setText("Calle:");
        jPanelEmpleado.add(jlbl_calle_direccion);
        jlbl_calle_direccion.setBounds(30, 270, 60, 15);

        jlbl_numero_direccion.setText("Número:");
        jPanelEmpleado.add(jlbl_numero_direccion);
        jlbl_numero_direccion.setBounds(30, 300, 60, 15);

        jlbl_piso_direccion.setText("Piso:");
        jPanelEmpleado.add(jlbl_piso_direccion);
        jlbl_piso_direccion.setBounds(30, 330, 60, 15);

        jlbl_departamento_direccion.setText("Departamento:");
        jPanelEmpleado.add(jlbl_departamento_direccion);
        jlbl_departamento_direccion.setBounds(30, 360, 90, 15);

        jPanelEmpleado.add(jcb_localidad_direccion);
        jcb_localidad_direccion.setBounds(140, 230, 180, 24);
        jPanelEmpleado.add(jtf_calle_direccion);
        jtf_calle_direccion.setBounds(140, 270, 180, 19);
        jPanelEmpleado.add(jtf_numero_direccion);
        jtf_numero_direccion.setBounds(140, 300, 180, 19);
        jPanelEmpleado.add(jtf_piso_direccion);
        jtf_piso_direccion.setBounds(140, 330, 180, 19);
        jPanelEmpleado.add(jtf_departamento_direccion);
        jtf_departamento_direccion.setBounds(140, 360, 180, 19);

        jlbl_cuit.setText("CUIT:");
        jPanelEmpleado.add(jlbl_cuit);
        jlbl_cuit.setBounds(30, 110, 100, 15);
        jPanelEmpleado.add(jtf_Cuit);
        jtf_Cuit.setBounds(140, 110, 180, 19);

        add(jPanelEmpleado);
        jPanelEmpleado.setBounds(60, 60, 725, 430);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelEmpleado;
    private javax.swing.JButton jbtn_Volver;
    private javax.swing.JComboBox<String> jcb_localidad_direccion;
    private javax.swing.JComboBox<String> jcb_provincia_direccion;
    private javax.swing.JComboBox<String> jcb_zona_direccion;
    private javax.swing.JLabel jlbl_ID;
    private javax.swing.JLabel jlbl_RazonSocial;
    private javax.swing.JLabel jlbl_calle_direccion;
    private javax.swing.JLabel jlbl_cuit;
    private javax.swing.JLabel jlbl_departamento_direccion;
    private javax.swing.JLabel jlbl_localidad_direccion;
    private javax.swing.JLabel jlbl_numero_direccion;
    private javax.swing.JLabel jlbl_piso_direccion;
    private javax.swing.JLabel jlbl_provincia_direccion;
    private javax.swing.JLabel jlbl_zona_direccion;
    private javax.swing.JTextField jtf_Cuit;
    private javax.swing.JTextField jtf_ID;
    private javax.swing.JTextField jtf_RazonSocial;
    private javax.swing.JTextField jtf_calle_direccion;
    private javax.swing.JTextField jtf_departamento_direccion;
    private javax.swing.JTextField jtf_numero_direccion;
    private javax.swing.JTextField jtf_piso_direccion;
    private javax.swing.JLabel msj_Apellido;
    private javax.swing.JLabel msj_DNI;
    private javax.swing.JLabel msj_Direccion;
    private javax.swing.JLabel msj_ID;
    private javax.swing.JLabel msj_Nombre;
    // End of variables declaration//GEN-END:variables

    
    public void setControlador(Controller c) {
        
        //Agrega Botones al Escuchador ActionListener para manejar los eventos realizados            
        jbtn_Volver.addActionListener(c);  
        
        //Agrega JTextField del Panel Datos del Empleado al escuchador KeyListener para verificar campos ingresados
        jtf_RazonSocial.addKeyListener(c);
        jtf_Cuit.addActionListener(c);
        
        
        //Agrega JTextField del Panel Direccion al escuchador KeyListener para verificar campos ingresados
        jtf_calle_direccion.addKeyListener(c);
        jtf_numero_direccion.addKeyListener(c);
        jtf_piso_direccion.addKeyListener(c);
        jtf_departamento_direccion.addKeyListener(c);
        
        //Agrega JcomboBox del Panel Direccion al escuchador ItemListener para verificar items seleccionados
        jcb_zona_direccion.addItemListener(c);
        jcb_provincia_direccion.addItemListener(c);
        jcb_localidad_direccion.addItemListener(c);
        
        //Agrega JcomboBox del Panel Direccion al escuchador ItemListener para verificar items seleccionados
        jcb_zona_direccion.addFocusListener(c);
        jcb_provincia_direccion.addFocusListener(c);
        jcb_localidad_direccion.addFocusListener(c);
        
        
        
    }

    /*
    CAMPOS del PANEL Getters y Setters
    */    
   
    public javax.swing.JTextField getJtfID() {
        return jtf_ID;
    }

    public void setJtfID(javax.swing.JTextField jtfID) {
        this.jtf_ID = jtfID;
    }

    public javax.swing.JTextField getJtfRazonSocial() {
        return jtf_RazonSocial;
    }

    public void setJtfRazonSocial(javax.swing.JTextField jtfNombre) {
        this.jtf_RazonSocial = jtfNombre;
    }
    
    public javax.swing.JTextField getJtf_Cuit() {
        return jtf_Cuit;
    }

    public void setJtf_Cuit(javax.swing.JTextField jtf_Cuit) {
        this.jtf_Cuit = jtf_Cuit;
    }

    public javax.swing.JComboBox<String> getJcb_localidad_direccion() {
        return jcb_localidad_direccion;
    }

    public void setJcb_localidad_direccion(javax.swing.JComboBox<String> jcb_localidad_direccion) {
        this.jcb_localidad_direccion = jcb_localidad_direccion;
    }

    public javax.swing.JComboBox<String> getJcb_provincia_direccion() {
        return jcb_provincia_direccion;
    }

    public void setJcb_provincia_direccion(javax.swing.JComboBox<String> jcb_provincia_direccion) {
        this.jcb_provincia_direccion = jcb_provincia_direccion;
    }

    public javax.swing.JComboBox<String> getJcb_zona_direccion() {
        return jcb_zona_direccion;
    }

    public void setJcb_zona_direccion(javax.swing.JComboBox<String> jcb_zona_direccion) {
        this.jcb_zona_direccion = jcb_zona_direccion;
    }

    public javax.swing.JTextField getJtf_calle_direccion() {
        return jtf_calle_direccion;
    }

    public void setJtf_calle_direccion(javax.swing.JTextField jtf_calle_direccion) {
        this.jtf_calle_direccion = jtf_calle_direccion;
    }

    public javax.swing.JTextField getJtf_departamento_direccion() {
        return jtf_departamento_direccion;
    }

    public void setJtf_departamento_direccion(javax.swing.JTextField jtf_departamento_direccion) {
        this.jtf_departamento_direccion = jtf_departamento_direccion;
    }

    public javax.swing.JTextField getJtf_numero_direccion() {
        return jtf_numero_direccion;
    }

    public void setJtf_numero_direccion(javax.swing.JTextField jtf_numero_direccion) {
        this.jtf_numero_direccion = jtf_numero_direccion;
    }

    public javax.swing.JTextField getJtf_piso_direccion() {
        return jtf_piso_direccion;
    }

    public void setJtf_piso_direccion(javax.swing.JTextField jtf_piso_direccion) {
        this.jtf_piso_direccion = jtf_piso_direccion;
    }
    
    
    
    /*
    BOTONES del PANEL
    */
           

    public javax.swing.JButton getJbtn_Volver() {
        return jbtn_Volver;
    }
      
    
    
    @Override
    public void limpiarCampo(JTextField campo){
        campo.setText("");        
    }
    
    @Override
    public void habilitarCampo(boolean h, JTextField campo){
        campo.setEditable(h);
        
    }

    @Override
   public void habilitarBoton(boolean h, JButton btn){
       btn.setEnabled(h);
   }

    @Override
    public ValidadorDeCampos getValidador() {
        return validador;
    }
    

    @Override
    public void habilitarCombobox(boolean h, JComboBox campo) {
        campo.setEnabled(h);
    }

    @Override
    public void limpiarCombobox(JComboBox campo) {
        campo.removeAllItems();
    }
   

    public javax.swing.JPanel getjPanelEmpleado() {
        return jPanelEmpleado;
    }

    

    

    
}
